FROM ubuntu:16.04

RUN apt-get update && apt-get install -y \
    golang \
    btrfs-tools \
    git-core \
    libdevmapper-dev \
    libgpgme11-dev \
    go-md2man

ENV GOPATH=/
WORKDIR /src/github.com/projectatomic/skopeo
