FROM ubuntu:17.04

RUN apt-get update && apt-get install -y \
    golang \
    btrfs-tools \
    git-core \
    libdevmapper-dev \
    libgpgme11-dev \
    go-md2man \
    libglib2.0-dev \
    libostree-dev

ENV GOPATH=/
WORKDIR /src/github.com/projectatomic/skopeo
