#!/bin/bash
set -e

bundle_test_integration() {
	TESTFLAGS="$TESTFLAGS -check.v"
	go_test_dir ./integration
}

# subshell so that we can export PATH without breaking other things
(
	make bin/skopeo ${BUILDTAGS:+BUILDTAGS="$BUILDTAGS"}
	make install
	bundle_test_integration
) 2>&1
